DROP TABLE IF EXISTS contacts;

CREATE TABLE contacts (
		id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(50) NOT NULL,
		email VARCHAR(100) NOT NULL,
		message VARCHAR(1000) NOT NULL,
		contact_date date NOT NULL,
		notes VARCHAR(1000) NULL,
		resolved BOOLEAN NOT NULL

);


insert into contacts (name, email, resolved, message, contact_date, notes) values ('Van Vasilechko', 'vvasilechko0@webnode.com', true, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2017-01-16 18:23:37', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Katrine Witson', 'kwitson1@chicagotribune.com', true, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2017-03-06 11:20:49', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Meredeth Parfett', 'mparfett2@histats.com', false, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2017-02-11 17:28:22', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Andrei Tuting', 'atuting3@smugmug.com', true, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2017-10-24 21:09:53', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Adrianna Vaune', 'avaune4@smh.com.au', false, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2017-04-06 15:35:12', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Stella O''Flaverty', 'soflaverty5@youtu.be', false, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2016-11-08 13:03:25', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Lynnette Peterffy', 'lpeterffy6@psu.edu', false, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2017-03-04 00:51:17', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Ilyse Grandisson', 'igrandisson7@nymag.com', false, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2017-09-11 17:12:36', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Rebecka Adenot', 'radenot8@csmonitor.com', false, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2016-11-29 09:20:03', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Ola Yanshonok', 'oyanshonok9@loc.gov', true, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2017-07-19 03:02:07', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Katharine Ablewhite', 'kablewhitea@mysql.com', true, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2017-03-19 21:49:45', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Effie Hark', 'eharkb@51.la', false, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2017-05-18 12:25:27', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Garvin Paige', 'gpaigec@illinois.edu', true, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2016-11-03 16:45:34', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Lyman Guidelli', 'lguidellid@samsung.com', false, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2017-10-14 10:24:36', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Brandie Greeves', 'bgreevese@timesonline.co.uk', true, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2017-04-19 11:39:16', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Anna-maria Drews', 'adrewsf@drupal.org', false, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2017-03-26 04:14:08', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Irwinn Nelsey', 'inelseyg@photobucket.com', true, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2017-09-10 20:13:03', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Julian Bendley', 'jbendleyh@samsung.com', true, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2017-08-25 23:43:41', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Ignazio Meys', 'imeysi@thetimes.co.uk', true, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2017-10-04 12:38:19', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into contacts (name, email, resolved, message, contact_date, notes) values ('Novelia Voaden', 'nvoadenj@thetimes.co.uk', false, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2017-03-29 06:53:16', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
